package:
  name: flyem_syn_eval
  version: "0.0.2"

source:
  git_rev: v0.0.2
  git_url: https://github.com/janelia-flyem/flyem_syn_eval.git

requirements:
  build:
    - python 2.7*
    - setuptools
  run:
    - python 2.7*
    - libdvid-cpp
    - numpy
    - pulp

about:
  home: https://github.com/janelia-flyem/flyem_syn_eval
  license: BSD (3-clause)
